open_triangle <- function(
    cws = FALSE,
    pred = FALSE,
    covariates = FALSE,
    ref_network = FALSE) {
  stopifnot(
    "current dir is not in case_study_triangle" =
      basename(getwd()) == "case_study_triangle"
  )
  data <- list()

  # Area of interest
  path <- paste0("./input/", "500Cities_City_11082016/CityBoundaries.shp")
  data$plot_shp <- terra::vect(path)
  data$plot_shp <- data$plot_shp[which(data$plot_shp$NAME %in%
    c("Raleigh", "Durham", "Cary")), ]
  # Create a rectangle around the Triangle area
  data$area_rect <- terra::ext(data$plot_shp) |>
    terra::as.polygons(crs = terra::crs(data$plot_shp)) |>
    terra::buffer(10000, joinstyle = "mitre")
  terra::plot(data$area_rect)
  terra::plot(data$plot_shp, col = "red", add = TRUE)


  saveRDS(pred, "./input/pred_grid.rds")

  if (pred == TRUE) {
    data$pred <- readRDS(paste0(
      "./input/",
      "grid_800_801_with_covar_202107.rds"
    ))

    # Open prediction grids covering this polygon
    # find_cells(data$area_rect)
    # pred1 <- readRDS("./input/grid_800_with_covar_202107.rds")
    # pred1 <- sf::st_transform(pred1, crs = 4326)
    # pred1$lon <- sf::st_coordinates(pred1)[, 1]
    # pred1$lat <- sf::st_coordinates(pred1)[, 2]
    # pred1 <- as.data.frame(pred1, xy = TRUE)

    # pred2 <- readRDS("./input/grid_801_with_covar_202107.rds")
    # pred2 <- sf::st_transform(pred2, crs = 4326)
    # pred2$lon <- sf::st_coordinates(pred2)[, 1]
    # pred2$lat <- sf::st_coordinates(pred2)[, 2]
    # pred2 <- as.data.frame(pred2, xy = TRUE)

    # pred <- rbind(pred1, pred2)
    # saveRDS(pred,
    #   file = paste0("./input/grid_800_801_with_covar_202107.rds")
    # )
    # write.csv(pred,
    #   file = paste0("./input/grid_800_801_with_covar_202107.csv")
    # )
  }

  if (cws == TRUE) {
    # Open CWS data generated by brassens library

    data$cws <- readRDS(paste0(
      "./input/",
      "cws/cws_covar_nc_2021-07.rds"
    ))
    # create an sf
    data$cws <- data$cws |>
      terra::vect(geom = c("lon", "lat"), crs = "epsg:4326") |>
      terra::project(data$area_rect) |>
      terra::intersect(data$area_rect) |>
      terra::project("epsg:4326") |>
      as.data.frame(geom = "xy") |>
      dplyr::rename(lon = "x", lat = "y")
  }

  if (covariates == TRUE) {
    data$era5 <- terra::rast("../input/era5_2021_07.nc")
    imp_path <- "../input/data_files/nlcd_2021_impervious_l48_20230630.img"
    imp <- terra::rast(imp_path)
    tcc_path <- paste0(
      "../input/nlcd_tcc_CONUS_2021_v2021-4/",
      "nlcd_tcc_conus_2021_v2021-4.tif"
    )
    tcc <- terra::rast(tcc_path)
    fch_path <- "../input/data_files/forest_height_2019_nam.tif"
    fch <- terra::rast(fch_path)
    bf_path <- "../input/bldgSum.img"
    bf <- terra::rast(bf_path)
    lcz_path <- "../input/lcz_conus_demuzere_2020.tif"
    lcz <- terra::rast(lcz_path)
    elev_path <- "../input/gmted_medianstat_7-5arcsec.tif"
    elev <- terra::rast(elev_path)
    modis_et_path <- "../input/MOD16A3GF.A2021001.h11v05.061.2022024075249.hdf"
    modis_et <- terra::sds(modis_et_path)

    data$elev <- process_elev(elev = elev, polygon = data$area_rect)
    data$lcz <- process_lcz(lcz = lcz, polygon = data$area_rect)
    data$imp <- process_imp(imp = imp, polygon = data$area_rect)
    data$tcc <- process_tcc(tcc = tcc, polygon = data$area_rect)
    data$fch <- process_fch(fch = fch, polygon = data$area_rect)
    data$bf <- process_bf(bf = bf, polygon = data$area_rect)
    data$et <- process_et(modis_et = modis_et, polygon = data$area_rect)
  }

  if (ref_network == TRUE) {
    source("open_econet.R")
    data$ref <- open_econet(f_path = "./input/econet/")
  }
  return(data)
}
