open_phi_nyc <- function(
    cws = FALSE,
    pred = FALSE,
    covariates = FALSE,
    ref_network = FALSE,
    path = NULL) {
  stopifnot(
    "current dir is not in case_study_phi_nyc" =
      basename(ifelse(is.null(path), getwd(), path)) == "case_study_phi_nyc"
  )
  data <- list()

  # Area of interest
  area_path <- paste0(path, "../input/", "500Cities_City_11082016/CityBoundaries.shp")
  data$plot_shp <- terra::vect(area_path)
  phi_nyc <- data$plot_shp[which(data$plot_shp$ST %in% c("NJ", "NY", "PA")), ]
  data$plot_shp <- phi_nyc[which(!(phi_nyc$NAME %in% c("Buffalo", "Pittsburgh", "Erie", "Rochester", "Syracuse", "Schenectady", "Albany", "Scranton", "Reading"))), ]

  terra::plot(data$plot_shp)
  terra::text(data$plot_shp, labels = "NAME")


  # Create a rectangle around New York and Philadelphia area
  data$area_rect <- terra::ext(data$plot_shp) |>
    terra::as.polygons(crs = terra::crs(data$plot_shp)) |>
    terra::buffer(15000, joinstyle = "mitre")
  terra::plot(data$area_rect)
  terra::plot(data$plot_shp, col = "red", add = TRUE)


  if (pred == TRUE) {
    data$pred <- readRDS(
      paste0(
        path, 
        "./input/grid_full_with_covar_202407.rds"
      )
    )
  } 

  if (cws == TRUE) {
    # Open CWS data generated by brassens library
    data$cws <- readRDS(paste0(
      path,
      "./input/",
      "cws/cws_covar_2024-07.rds"
    ))
    if (any(!c("lon", "lat") %in% colnames(data$cws))) {
      data$cws$lon <- sf::st_coordinates(data$cws$geometry)[, 1]
      data$cws$lat <- sf::st_coordinates(data$cws$geometry)[, 2]
    }
    # create an sf
    data$cws <- data$cws |>
      terra::vect(geom = c("lon", "lat"), crs = "epsg:4326") |>
      terra::project(data$area_rect) |>
      terra::intersect(data$area_rect) |>
      terra::project("epsg:4326") |>
      as.data.frame(geom = "xy") |>
      dplyr::rename(lon = "x", lat = "y")
  }

  if (covariates == TRUE) {
    path_instant <- paste0(
      path,
      "../input/era5_us_2024_07/",
      "data_stream-oper_stepType-instant.nc"
    )
    path_accum <- paste0(
      path,
      "../input/era5_us_2024_07/",
      "data_stream-oper_stepType-accum.nc"
    )
    data$era5_instant <- terra::rast(path_instant)
    data$era5_accum <- terra::rast(path_accum)
    imp_path <- paste0(
      path,
      "../input/data_files/nlcd_2021_impervious_l48_20230630.img"
    )
    imp <- terra::rast(imp_path)
    tcc_path <- paste0(
      path,
      "../input/nlcd_tcc_CONUS_2021_v2021-4/",
      "nlcd_tcc_conus_2021_v2021-4.tif"
    )
    tcc <- terra::rast(tcc_path)
    fch_path <- paste0(path, "../input/data_files/forest_height_2019_nam.tif")
    fch <- terra::rast(fch_path)
    bf_path <- paste0(path, "../input/bldgSum.img")
    bf <- terra::rast(bf_path)
    lcz_path <- paste0(path, "../input/lcz_conus_demuzere_2020.tif")
    lcz <- terra::rast(lcz_path)
    elev_path <- paste0(path, "../input/gmted_medianstat_7-5arcsec.tif")
    elev <- terra::rast(elev_path)
    data$elev <- process_elev(elev = elev, polygon = data$area_rect)
    data$lcz <- process_lcz(lcz = lcz, polygon = data$area_rect)
    data$imp <- process_imp(imp = imp, polygon = data$area_rect)
    data$tcc <- process_tcc(tcc = tcc, polygon = data$area_rect)
    data$fch <- process_fch(fch = fch, polygon = data$area_rect)
    data$bf <- process_bf(bf = bf, polygon = data$area_rect)
  }

  if (ref_network == TRUE) {
    source(paste0(path, "open_mesonet.R"))
    data$ref <- open_mesonet("202407", path)
  }
  return(data)
}
